git commit --allow-empty -m "First commit"
git commit --allow-empty -m "1"
git commit --allow-empty -m "2"
git commit --allow-empty -m "3"
git commit --allow-empty -m "4"
git commit --allow-empty -m "5"
git commit --allow-empty -m "6"
git commit --allow-empty -m "7"
git commit --allow-empty -m "8"
git commit --allow-empty -m "9"
git commit --allow-empty -m "10"
git commit --allow-empty -m "11"
git commit --allow-empty -m "12"
git commit --allow-empty -m "13"
git commit --allow-empty -m "14"
git commit --allow-empty -m "15"
git commit --allow-empty -m "16"
git commit --allow-empty -m "17"
git commit --allow-empty -m "18"
git commit --allow-empty -m "19"
git commit --allow-empty -m "20"
git commit --allow-empty -m "21"
git commit --allow-empty -m "22"
git commit --allow-empty -m "Latest commit"